// Package swagger Code generated by swaggo/swag. DO NOT EDIT
package swagger

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/healthz": {
            "get": {
                "description": "Returns agent health status, version, and enabled features. Does not require authentication.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_erikmagkekse_btrfs-nfs-csi_agent_api_v1_models.HealthResponse"
                        }
                    }
                }
            }
        },
        "/v1/clones": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Creates a new volume from a snapshot. Returns existing on conflict.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "clones"
                ],
                "summary": "Create a clone from snapshot",
                "parameters": [
                    {
                        "description": "Clone configuration",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_erikmagkekse_btrfs-nfs-csi_agent_api_v1_models.CloneCreateRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_erikmagkekse_btrfs-nfs-csi_agent_api_v1_models.VolumeDetailResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_erikmagkekse_btrfs-nfs-csi_agent_api_v1_models.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Volume already exists",
                        "schema": {
                            "$ref": "#/definitions/github_com_erikmagkekse_btrfs-nfs-csi_agent_api_v1_models.VolumeDetailResponse"
                        }
                    },
                    "423": {
                        "description": "Lock contention, retry",
                        "schema": {
                            "$ref": "#/definitions/github_com_erikmagkekse_btrfs-nfs-csi_agent_api_v1_models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/exports": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns all active NFS exports. Use detail=true for labels. Supports pagination and label filtering.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "exports"
                ],
                "summary": "List NFS exports",
                "parameters": [
                    {
                        "enum": [
                            "true"
                        ],
                        "type": "string",
                        "description": "Return full detail",
                        "name": "detail",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Items per page (0 = pagination disabled)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Pagination cursor",
                        "name": "after",
                        "in": "query"
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "collectionFormat": "csv",
                        "description": "Label filter (key=value), repeatable",
                        "name": "label",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_erikmagkekse_btrfs-nfs-csi_agent_api_v1_models.ExportListResponse"
                        }
                    }
                }
            }
        },
        "/v1/snapshots": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns all snapshots. Use detail=true for full metadata. Supports pagination and label filtering.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "snapshots"
                ],
                "summary": "List snapshots",
                "parameters": [
                    {
                        "enum": [
                            "true"
                        ],
                        "type": "string",
                        "description": "Return full detail",
                        "name": "detail",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Items per page (0 = pagination disabled)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Pagination cursor",
                        "name": "after",
                        "in": "query"
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "collectionFormat": "csv",
                        "description": "Label filter (key=value), repeatable",
                        "name": "label",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_erikmagkekse_btrfs-nfs-csi_agent_api_v1_models.SnapshotListResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Creates a read-only btrfs snapshot of a volume. Returns existing snapshot on conflict.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "snapshots"
                ],
                "summary": "Create a snapshot",
                "parameters": [
                    {
                        "description": "Snapshot configuration",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_erikmagkekse_btrfs-nfs-csi_agent_api_v1_models.SnapshotCreateRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_erikmagkekse_btrfs-nfs-csi_agent_api_v1_models.SnapshotDetailResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_erikmagkekse_btrfs-nfs-csi_agent_api_v1_models.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Snapshot already exists",
                        "schema": {
                            "$ref": "#/definitions/github_com_erikmagkekse_btrfs-nfs-csi_agent_api_v1_models.SnapshotDetailResponse"
                        }
                    },
                    "423": {
                        "description": "Lock contention, retry",
                        "schema": {
                            "$ref": "#/definitions/github_com_erikmagkekse_btrfs-nfs-csi_agent_api_v1_models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/snapshots/{name}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns detailed metadata for a single snapshot.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "snapshots"
                ],
                "summary": "Get a snapshot",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Snapshot name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_erikmagkekse_btrfs-nfs-csi_agent_api_v1_models.SnapshotDetailResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_erikmagkekse_btrfs-nfs-csi_agent_api_v1_models.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Deletes a snapshot and its btrfs subvolume.",
                "tags": [
                    "snapshots"
                ],
                "summary": "Delete a snapshot",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Snapshot name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_erikmagkekse_btrfs-nfs-csi_agent_api_v1_models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/stats": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns statfs and btrfs device/filesystem statistics.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "stats"
                ],
                "summary": "Get filesystem statistics",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_erikmagkekse_btrfs-nfs-csi_agent_api_v1_models.StatsResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_erikmagkekse_btrfs-nfs-csi_agent_api_v1_models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/tasks": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns background tasks. Filter by type. Supports detail, pagination, and label filtering.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tasks"
                ],
                "summary": "List tasks",
                "parameters": [
                    {
                        "enum": [
                            "scrub",
                            "test"
                        ],
                        "type": "string",
                        "description": "Filter by task type",
                        "name": "type",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "true"
                        ],
                        "type": "string",
                        "description": "Return full detail",
                        "name": "detail",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Items per page (0 = pagination disabled)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Pagination cursor",
                        "name": "after",
                        "in": "query"
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "collectionFormat": "csv",
                        "description": "Label filter (key=value), repeatable",
                        "name": "label",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_erikmagkekse_btrfs-nfs-csi_agent_api_v1_models.TaskListResponse"
                        }
                    }
                }
            }
        },
        "/v1/tasks/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns detailed metadata for a single background task.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tasks"
                ],
                "summary": "Get a task",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Task ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_erikmagkekse_btrfs-nfs-csi_agent_api_v1_models.TaskDetailResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_erikmagkekse_btrfs-nfs-csi_agent_api_v1_models.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Cancels a running or pending background task.",
                "tags": [
                    "tasks"
                ],
                "summary": "Cancel a task",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Task ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_erikmagkekse_btrfs-nfs-csi_agent_api_v1_models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/tasks/{type}": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Creates a background task (scrub or test). Returns 202 Accepted with task ID.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tasks"
                ],
                "summary": "Create a background task",
                "parameters": [
                    {
                        "enum": [
                            "scrub",
                            "test"
                        ],
                        "type": "string",
                        "description": "Task type",
                        "name": "type",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Task options",
                        "name": "request",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/github_com_erikmagkekse_btrfs-nfs-csi_agent_api_v1_models.TaskCreateRequest"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "$ref": "#/definitions/github_com_erikmagkekse_btrfs-nfs-csi_agent_api_v1_models.TaskCreateResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_erikmagkekse_btrfs-nfs-csi_agent_api_v1_models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/volumes": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns all volumes. Use detail=true for full metadata. Supports pagination and label filtering.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "volumes"
                ],
                "summary": "List volumes",
                "parameters": [
                    {
                        "enum": [
                            "true"
                        ],
                        "type": "string",
                        "description": "Return full detail",
                        "name": "detail",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Items per page (0 = pagination disabled)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Pagination cursor from previous response",
                        "name": "after",
                        "in": "query"
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "collectionFormat": "csv",
                        "description": "Label filter (key=value), repeatable",
                        "name": "label",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_erikmagkekse_btrfs-nfs-csi_agent_api_v1_models.VolumeListResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Creates a new btrfs subvolume. Returns the existing volume on conflict.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "volumes"
                ],
                "summary": "Create a volume",
                "parameters": [
                    {
                        "description": "Volume configuration",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_erikmagkekse_btrfs-nfs-csi_agent_api_v1_models.VolumeCreateRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_erikmagkekse_btrfs-nfs-csi_agent_api_v1_models.VolumeDetailResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_erikmagkekse_btrfs-nfs-csi_agent_api_v1_models.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Volume already exists",
                        "schema": {
                            "$ref": "#/definitions/github_com_erikmagkekse_btrfs-nfs-csi_agent_api_v1_models.VolumeDetailResponse"
                        }
                    },
                    "423": {
                        "description": "Lock contention, retry",
                        "schema": {
                            "$ref": "#/definitions/github_com_erikmagkekse_btrfs-nfs-csi_agent_api_v1_models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/volumes/clone": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Creates a new volume from another volume (internal snapshot + clone). Returns existing on conflict.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "clones"
                ],
                "summary": "Clone a volume",
                "parameters": [
                    {
                        "description": "Clone configuration",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_erikmagkekse_btrfs-nfs-csi_agent_api_v1_models.VolumeCloneRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_erikmagkekse_btrfs-nfs-csi_agent_api_v1_models.VolumeDetailResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_erikmagkekse_btrfs-nfs-csi_agent_api_v1_models.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Volume already exists",
                        "schema": {
                            "$ref": "#/definitions/github_com_erikmagkekse_btrfs-nfs-csi_agent_api_v1_models.VolumeDetailResponse"
                        }
                    },
                    "423": {
                        "description": "Lock contention, retry",
                        "schema": {
                            "$ref": "#/definitions/github_com_erikmagkekse_btrfs-nfs-csi_agent_api_v1_models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/volumes/{name}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns detailed metadata for a single volume.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "volumes"
                ],
                "summary": "Get a volume",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Volume name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_erikmagkekse_btrfs-nfs-csi_agent_api_v1_models.VolumeDetailResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_erikmagkekse_btrfs-nfs-csi_agent_api_v1_models.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Deletes a volume and its btrfs subvolume. Fails if the volume has active exports.",
                "tags": [
                    "volumes"
                ],
                "summary": "Delete a volume",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Volume name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_erikmagkekse_btrfs-nfs-csi_agent_api_v1_models.ErrorResponse"
                        }
                    },
                    "423": {
                        "description": "Volume has active exports",
                        "schema": {
                            "$ref": "#/definitions/github_com_erikmagkekse_btrfs-nfs-csi_agent_api_v1_models.ErrorResponse"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Patches volume properties. Nil/omitted fields are left unchanged.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "volumes"
                ],
                "summary": "Update a volume",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Volume name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Fields to update",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_erikmagkekse_btrfs-nfs-csi_agent_api_v1_models.VolumeUpdateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_erikmagkekse_btrfs-nfs-csi_agent_api_v1_models.VolumeDetailResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_erikmagkekse_btrfs-nfs-csi_agent_api_v1_models.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_erikmagkekse_btrfs-nfs-csi_agent_api_v1_models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/volumes/{name}/export": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Adds an NFS export for a volume to the given client IP.",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "exports"
                ],
                "summary": "Add NFS export",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Volume name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Export config",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_erikmagkekse_btrfs-nfs-csi_agent_api_v1_models.VolumeExportCreateRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_erikmagkekse_btrfs-nfs-csi_agent_api_v1_models.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_erikmagkekse_btrfs-nfs-csi_agent_api_v1_models.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Removes an NFS export for a volume from the given client IP.",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "exports"
                ],
                "summary": "Remove NFS export",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Volume name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Export to remove",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_erikmagkekse_btrfs-nfs-csi_agent_api_v1_models.VolumeExportDeleteRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_erikmagkekse_btrfs-nfs-csi_agent_api_v1_models.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_erikmagkekse_btrfs-nfs-csi_agent_api_v1_models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/volumes/{name}/snapshots": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns snapshots for a specific volume. Supports detail, pagination, and label filtering.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "snapshots"
                ],
                "summary": "List snapshots for a volume",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Volume name",
                        "name": "name",
                        "in": "path"
                    },
                    {
                        "enum": [
                            "true"
                        ],
                        "type": "string",
                        "description": "Return full detail",
                        "name": "detail",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Items per page",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Pagination cursor",
                        "name": "after",
                        "in": "query"
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "collectionFormat": "csv",
                        "description": "Label filter (key=value), repeatable",
                        "name": "label",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_erikmagkekse_btrfs-nfs-csi_agent_api_v1_models.SnapshotListResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_erikmagkekse_btrfs-nfs-csi_agent_api_v1_models.CloneCreateRequest": {
            "type": "object",
            "properties": {
                "labels": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "name": {
                    "description": "^[a-zA-Z0-9_-]{1,128}$",
                    "type": "string"
                },
                "snapshot": {
                    "description": "source snapshot name",
                    "type": "string"
                }
            }
        },
        "github_com_erikmagkekse_btrfs-nfs-csi_agent_api_v1_models.DeviceErrorsResponse": {
            "type": "object",
            "properties": {
                "corruption_errs": {
                    "description": "data corruption errors",
                    "type": "integer"
                },
                "flush_errs": {
                    "description": "flush errors",
                    "type": "integer"
                },
                "generation_errs": {
                    "description": "generation mismatch errors",
                    "type": "integer"
                },
                "read_errs": {
                    "description": "read errors",
                    "type": "integer"
                },
                "write_errs": {
                    "description": "write errors",
                    "type": "integer"
                }
            }
        },
        "github_com_erikmagkekse_btrfs-nfs-csi_agent_api_v1_models.DeviceIOStatsResponse": {
            "type": "object",
            "properties": {
                "io_time_ms_total": {
                    "description": "total I/O time in milliseconds",
                    "type": "integer"
                },
                "ios_in_progress": {
                    "description": "I/O operations currently in flight",
                    "type": "integer"
                },
                "read_bytes_total": {
                    "description": "total bytes read",
                    "type": "integer"
                },
                "read_ios_total": {
                    "description": "total read I/O operations",
                    "type": "integer"
                },
                "read_time_ms_total": {
                    "description": "total read time in milliseconds",
                    "type": "integer"
                },
                "weighted_io_time_ms_total": {
                    "description": "weighted I/O time in milliseconds",
                    "type": "integer"
                },
                "write_bytes_total": {
                    "description": "total bytes written",
                    "type": "integer"
                },
                "write_ios_total": {
                    "description": "total write I/O operations",
                    "type": "integer"
                },
                "write_time_ms_total": {
                    "description": "total write time in milliseconds",
                    "type": "integer"
                }
            }
        },
        "github_com_erikmagkekse_btrfs-nfs-csi_agent_api_v1_models.DeviceStatsResponse": {
            "type": "object",
            "properties": {
                "allocated_bytes": {
                    "description": "bytes allocated on this device",
                    "type": "integer"
                },
                "device": {
                    "description": "block device path (e.g. \"/dev/sda1\")",
                    "type": "string"
                },
                "devid": {
                    "description": "btrfs device ID",
                    "type": "string"
                },
                "errors": {
                    "description": "btrfs error counters",
                    "allOf": [
                        {
                            "$ref": "#/definitions/github_com_erikmagkekse_btrfs-nfs-csi_agent_api_v1_models.DeviceErrorsResponse"
                        }
                    ]
                },
                "io": {
                    "description": "I/O counters from /sys/block",
                    "allOf": [
                        {
                            "$ref": "#/definitions/github_com_erikmagkekse_btrfs-nfs-csi_agent_api_v1_models.DeviceIOStatsResponse"
                        }
                    ]
                },
                "missing": {
                    "description": "true if device is missing from the filesystem",
                    "type": "boolean"
                },
                "size_bytes": {
                    "description": "device size in bytes",
                    "type": "integer"
                }
            }
        },
        "github_com_erikmagkekse_btrfs-nfs-csi_agent_api_v1_models.ErrorResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "error": {
                    "type": "string"
                }
            }
        },
        "github_com_erikmagkekse_btrfs-nfs-csi_agent_api_v1_models.ExportDetailResponse": {
            "type": "object",
            "properties": {
                "client": {
                    "description": "client IP address (IPv4 or IPv6)",
                    "type": "string"
                },
                "created_at": {
                    "description": "creation timestamp (UTC)",
                    "type": "string"
                },
                "created_by": {
                    "description": "identity that created this export",
                    "type": "string"
                },
                "labels": {
                    "description": "user-defined labels",
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "name": {
                    "description": "volume name",
                    "type": "string"
                }
            }
        },
        "github_com_erikmagkekse_btrfs-nfs-csi_agent_api_v1_models.ExportListResponse": {
            "type": "object",
            "properties": {
                "exports": {
                    "description": "list of exports",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_erikmagkekse_btrfs-nfs-csi_agent_api_v1_models.ExportResponse"
                    }
                },
                "next": {
                    "description": "opaque cursor for the next page",
                    "type": "string"
                },
                "total": {
                    "description": "total number of exports matching the query",
                    "type": "integer"
                }
            }
        },
        "github_com_erikmagkekse_btrfs-nfs-csi_agent_api_v1_models.ExportResponse": {
            "type": "object",
            "properties": {
                "client": {
                    "description": "client IP address (IPv4 or IPv6)",
                    "type": "string"
                },
                "created_at": {
                    "description": "creation timestamp (UTC)",
                    "type": "string"
                },
                "created_by": {
                    "description": "identity that created this export",
                    "type": "string"
                },
                "name": {
                    "description": "volume name",
                    "type": "string"
                }
            }
        },
        "github_com_erikmagkekse_btrfs-nfs-csi_agent_api_v1_models.FilesystemStatsResponse": {
            "type": "object",
            "properties": {
                "data_ratio": {
                    "description": "data replication ratio (e.g. 1.0 for single, 2.0 for RAID1)",
                    "type": "number"
                },
                "devices": {
                    "description": "per-device statistics",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_erikmagkekse_btrfs-nfs-csi_agent_api_v1_models.DeviceStatsResponse"
                    }
                },
                "free_bytes": {
                    "description": "bytes free (total - used)",
                    "type": "integer"
                },
                "metadata_total_bytes": {
                    "description": "metadata bytes allocated",
                    "type": "integer"
                },
                "metadata_used_bytes": {
                    "description": "metadata bytes used",
                    "type": "integer"
                },
                "total_bytes": {
                    "description": "total filesystem size in bytes",
                    "type": "integer"
                },
                "unallocated_bytes": {
                    "description": "bytes not yet allocated to any chunk",
                    "type": "integer"
                },
                "used_bytes": {
                    "description": "bytes used",
                    "type": "integer"
                }
            }
        },
        "github_com_erikmagkekse_btrfs-nfs-csi_agent_api_v1_models.HealthResponse": {
            "type": "object",
            "properties": {
                "commit": {
                    "description": "git commit hash",
                    "type": "string"
                },
                "status": {
                    "description": "\"ok\" or \"degraded\"",
                    "type": "string"
                },
                "uptime_seconds": {
                    "description": "seconds since agent start",
                    "type": "integer"
                },
                "version": {
                    "description": "agent version string",
                    "type": "string"
                }
            }
        },
        "github_com_erikmagkekse_btrfs-nfs-csi_agent_api_v1_models.SnapshotCreateRequest": {
            "type": "object",
            "properties": {
                "labels": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "name": {
                    "description": "^[a-zA-Z0-9_-]{1,128}$",
                    "type": "string"
                },
                "volume": {
                    "description": "source volume name",
                    "type": "string"
                }
            }
        },
        "github_com_erikmagkekse_btrfs-nfs-csi_agent_api_v1_models.SnapshotDetailResponse": {
            "type": "object",
            "properties": {
                "compression": {
                    "description": "compression algorithm from source volume",
                    "type": "string"
                },
                "created_at": {
                    "description": "creation timestamp (UTC)",
                    "type": "string"
                },
                "created_by": {
                    "description": "identity that created this snapshot",
                    "type": "string"
                },
                "exclusive_bytes": {
                    "description": "exclusive bytes (not shared with other snapshots)",
                    "type": "integer"
                },
                "gid": {
                    "description": "owner GID from source volume",
                    "type": "integer"
                },
                "labels": {
                    "description": "user-defined labels",
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "mode": {
                    "description": "permission mode from source volume",
                    "type": "string"
                },
                "name": {
                    "description": "snapshot name",
                    "type": "string"
                },
                "nocow": {
                    "description": "copy-on-write disabled on source volume",
                    "type": "boolean"
                },
                "path": {
                    "description": "absolute path on the agent host",
                    "type": "string"
                },
                "quota_bytes": {
                    "description": "Source volume properties, preserved for clone fallback.",
                    "type": "integer"
                },
                "size_bytes": {
                    "description": "size in bytes (from source volume at snapshot time)",
                    "type": "integer"
                },
                "uid": {
                    "description": "owner UID from source volume",
                    "type": "integer"
                },
                "updated_at": {
                    "description": "last update timestamp (UTC)",
                    "type": "string"
                },
                "used_bytes": {
                    "description": "bytes used (btrfs qgroup accounting)",
                    "type": "integer"
                },
                "volume": {
                    "description": "source volume name",
                    "type": "string"
                }
            }
        },
        "github_com_erikmagkekse_btrfs-nfs-csi_agent_api_v1_models.SnapshotListResponse": {
            "type": "object",
            "properties": {
                "next": {
                    "description": "opaque cursor for the next page",
                    "type": "string"
                },
                "snapshots": {
                    "description": "list of snapshots",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_erikmagkekse_btrfs-nfs-csi_agent_api_v1_models.SnapshotResponse"
                    }
                },
                "total": {
                    "description": "total number of snapshots matching the query",
                    "type": "integer"
                }
            }
        },
        "github_com_erikmagkekse_btrfs-nfs-csi_agent_api_v1_models.SnapshotResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "description": "creation timestamp (UTC)",
                    "type": "string"
                },
                "created_by": {
                    "description": "identity that created this snapshot",
                    "type": "string"
                },
                "name": {
                    "description": "snapshot name",
                    "type": "string"
                },
                "size_bytes": {
                    "description": "size in bytes (from source volume at snapshot time)",
                    "type": "integer"
                },
                "used_bytes": {
                    "description": "bytes used (btrfs qgroup accounting)",
                    "type": "integer"
                },
                "volume": {
                    "description": "source volume name",
                    "type": "string"
                }
            }
        },
        "github_com_erikmagkekse_btrfs-nfs-csi_agent_api_v1_models.StatfsResponse": {
            "type": "object",
            "properties": {
                "free_bytes": {
                    "description": "bytes free",
                    "type": "integer"
                },
                "total_bytes": {
                    "description": "total filesystem size in bytes",
                    "type": "integer"
                },
                "used_bytes": {
                    "description": "bytes used",
                    "type": "integer"
                }
            }
        },
        "github_com_erikmagkekse_btrfs-nfs-csi_agent_api_v1_models.StatsResponse": {
            "type": "object",
            "properties": {
                "btrfs": {
                    "description": "btrfs-specific filesystem statistics",
                    "allOf": [
                        {
                            "$ref": "#/definitions/github_com_erikmagkekse_btrfs-nfs-csi_agent_api_v1_models.FilesystemStatsResponse"
                        }
                    ]
                },
                "statfs": {
                    "description": "statfs(2) counters",
                    "allOf": [
                        {
                            "$ref": "#/definitions/github_com_erikmagkekse_btrfs-nfs-csi_agent_api_v1_models.StatfsResponse"
                        }
                    ]
                },
                "tenant_name": {
                    "description": "tenant name",
                    "type": "string"
                }
            }
        },
        "github_com_erikmagkekse_btrfs-nfs-csi_agent_api_v1_models.TaskCreateRequest": {
            "type": "object",
            "properties": {
                "labels": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "opts": {
                    "description": "task-specific options",
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "timeout": {
                    "description": "Go duration string, e.g. \"6h\", \"30m\"",
                    "type": "string"
                }
            }
        },
        "github_com_erikmagkekse_btrfs-nfs-csi_agent_api_v1_models.TaskCreateResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "description": "initial status (\"pending\")",
                    "type": "string"
                },
                "task_id": {
                    "description": "unique task ID (UUID)",
                    "type": "string"
                }
            }
        },
        "github_com_erikmagkekse_btrfs-nfs-csi_agent_api_v1_models.TaskDetailResponse": {
            "type": "object",
            "properties": {
                "completed_at": {
                    "description": "completion timestamp (UTC)",
                    "type": "string"
                },
                "created_at": {
                    "description": "creation timestamp (UTC)",
                    "type": "string"
                },
                "created_by": {
                    "description": "identity that created this task",
                    "type": "string"
                },
                "error": {
                    "description": "error message if failed",
                    "type": "string"
                },
                "id": {
                    "description": "unique task ID (UUID)",
                    "type": "string"
                },
                "labels": {
                    "description": "user-defined labels",
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "opts": {
                    "description": "task-specific options",
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "progress": {
                    "description": "completion percentage (0-100)",
                    "type": "integer"
                },
                "result": {
                    "description": "task-specific result payload (JSON)",
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "started_at": {
                    "description": "execution start timestamp (UTC)",
                    "type": "string"
                },
                "status": {
                    "description": "\"pending\", \"running\", \"completed\", \"failed\", \"cancelled\"",
                    "type": "string"
                },
                "timeout": {
                    "description": "Go duration string (e.g. \"6h\")",
                    "type": "string"
                },
                "type": {
                    "description": "task type (\"scrub\", \"test\")",
                    "type": "string"
                }
            }
        },
        "github_com_erikmagkekse_btrfs-nfs-csi_agent_api_v1_models.TaskListResponse": {
            "type": "object",
            "properties": {
                "next": {
                    "description": "opaque cursor for the next page",
                    "type": "string"
                },
                "tasks": {
                    "description": "list of tasks",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_erikmagkekse_btrfs-nfs-csi_agent_api_v1_models.TaskResponse"
                    }
                },
                "total": {
                    "description": "total number of tasks matching the query",
                    "type": "integer"
                }
            }
        },
        "github_com_erikmagkekse_btrfs-nfs-csi_agent_api_v1_models.TaskResponse": {
            "type": "object",
            "properties": {
                "completed_at": {
                    "description": "completion timestamp (UTC)",
                    "type": "string"
                },
                "created_at": {
                    "description": "creation timestamp (UTC)",
                    "type": "string"
                },
                "created_by": {
                    "description": "identity that created this task",
                    "type": "string"
                },
                "error": {
                    "description": "error message if failed",
                    "type": "string"
                },
                "id": {
                    "description": "unique task ID (UUID)",
                    "type": "string"
                },
                "opts": {
                    "description": "task-specific options",
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "progress": {
                    "description": "completion percentage (0-100)",
                    "type": "integer"
                },
                "started_at": {
                    "description": "execution start timestamp (UTC)",
                    "type": "string"
                },
                "status": {
                    "description": "\"pending\", \"running\", \"completed\", \"failed\", \"cancelled\"",
                    "type": "string"
                },
                "timeout": {
                    "description": "Go duration string (e.g. \"6h\")",
                    "type": "string"
                },
                "type": {
                    "description": "task type (\"scrub\", \"test\")",
                    "type": "string"
                }
            }
        },
        "github_com_erikmagkekse_btrfs-nfs-csi_agent_api_v1_models.VolumeCloneRequest": {
            "type": "object",
            "properties": {
                "labels": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "name": {
                    "description": "^[a-zA-Z0-9_-]{1,128}$",
                    "type": "string"
                },
                "source": {
                    "description": "source volume name",
                    "type": "string"
                }
            }
        },
        "github_com_erikmagkekse_btrfs-nfs-csi_agent_api_v1_models.VolumeCreateRequest": {
            "type": "object",
            "properties": {
                "compression": {
                    "description": "\"zstd\", \"zstd:3\", \"zlib\", \"zlib:5\", \"lzo\", or \"\"",
                    "type": "string"
                },
                "gid": {
                    "description": "owner GID (0-65534)",
                    "type": "integer"
                },
                "labels": {
                    "description": "key: ^[a-z0-9][a-z0-9._-]{0,62}$, value: ^[a-zA-Z0-9._-]{0,128}$",
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "mode": {
                    "description": "octal permission string, e.g. \"0755\" (max 7777)",
                    "type": "string"
                },
                "name": {
                    "description": "^[a-zA-Z0-9_-]{1,128}$",
                    "type": "string"
                },
                "nocow": {
                    "description": "disable copy-on-write (chattr +C)",
                    "type": "boolean"
                },
                "quota_bytes": {
                    "description": "btrfs qgroup limit (0 = no quota)",
                    "type": "integer"
                },
                "size_bytes": {
                    "description": "subvolume size in bytes",
                    "type": "integer"
                },
                "uid": {
                    "description": "owner UID (0-65534)",
                    "type": "integer"
                }
            }
        },
        "github_com_erikmagkekse_btrfs-nfs-csi_agent_api_v1_models.VolumeDetailResponse": {
            "type": "object",
            "properties": {
                "clients": {
                    "description": "active NFS exports",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_erikmagkekse_btrfs-nfs-csi_agent_api_v1_models.ExportDetailResponse"
                    }
                },
                "compression": {
                    "description": "compression algorithm (e.g. \"zstd\", \"zlib\", \"lzo\", \"\")",
                    "type": "string"
                },
                "created_at": {
                    "description": "creation timestamp (UTC)",
                    "type": "string"
                },
                "created_by": {
                    "description": "identity that created this volume",
                    "type": "string"
                },
                "gid": {
                    "description": "owner GID",
                    "type": "integer"
                },
                "labels": {
                    "description": "user-defined labels",
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "last_attach_at": {
                    "description": "last NFS export attach timestamp (UTC)",
                    "type": "string"
                },
                "mode": {
                    "description": "octal permission string (e.g. \"0755\")",
                    "type": "string"
                },
                "name": {
                    "description": "volume name",
                    "type": "string"
                },
                "nocow": {
                    "description": "copy-on-write disabled (chattr +C)",
                    "type": "boolean"
                },
                "path": {
                    "description": "absolute path on the agent host",
                    "type": "string"
                },
                "quota_bytes": {
                    "description": "btrfs qgroup limit in bytes",
                    "type": "integer"
                },
                "size_bytes": {
                    "description": "subvolume size in bytes",
                    "type": "integer"
                },
                "uid": {
                    "description": "owner UID",
                    "type": "integer"
                },
                "updated_at": {
                    "description": "last update timestamp (UTC)",
                    "type": "string"
                },
                "used_bytes": {
                    "description": "bytes used (btrfs qgroup accounting)",
                    "type": "integer"
                }
            }
        },
        "github_com_erikmagkekse_btrfs-nfs-csi_agent_api_v1_models.VolumeExportCreateRequest": {
            "type": "object",
            "properties": {
                "client": {
                    "description": "client IP address (IPv4 or IPv6)",
                    "type": "string"
                },
                "labels": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                }
            }
        },
        "github_com_erikmagkekse_btrfs-nfs-csi_agent_api_v1_models.VolumeExportDeleteRequest": {
            "type": "object",
            "properties": {
                "client": {
                    "description": "client IP address (IPv4 or IPv6)",
                    "type": "string"
                },
                "labels": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                }
            }
        },
        "github_com_erikmagkekse_btrfs-nfs-csi_agent_api_v1_models.VolumeListResponse": {
            "type": "object",
            "properties": {
                "next": {
                    "description": "opaque cursor for the next page (empty on last page)",
                    "type": "string"
                },
                "total": {
                    "description": "total number of volumes matching the query",
                    "type": "integer"
                },
                "volumes": {
                    "description": "list of volumes",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_erikmagkekse_btrfs-nfs-csi_agent_api_v1_models.VolumeResponse"
                    }
                }
            }
        },
        "github_com_erikmagkekse_btrfs-nfs-csi_agent_api_v1_models.VolumeResponse": {
            "type": "object",
            "properties": {
                "clients": {
                    "description": "number of active NFS exports",
                    "type": "integer"
                },
                "created_at": {
                    "description": "creation timestamp (UTC)",
                    "type": "string"
                },
                "created_by": {
                    "description": "identity that created this volume (e.g. \"cli\", \"controller\")",
                    "type": "string"
                },
                "name": {
                    "description": "volume name",
                    "type": "string"
                },
                "size_bytes": {
                    "description": "subvolume size in bytes",
                    "type": "integer"
                },
                "used_bytes": {
                    "description": "bytes used (btrfs qgroup accounting)",
                    "type": "integer"
                }
            }
        },
        "github_com_erikmagkekse_btrfs-nfs-csi_agent_api_v1_models.VolumeUpdateRequest": {
            "type": "object",
            "properties": {
                "compression": {
                    "description": "see VolumeCreateRequest.Compression",
                    "type": "string"
                },
                "gid": {
                    "description": "new owner GID (0-65534)",
                    "type": "integer"
                },
                "labels": {
                    "description": "replaces all labels",
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "mode": {
                    "description": "octal permission string (max 7777)",
                    "type": "string"
                },
                "nocow": {
                    "description": "toggle copy-on-write",
                    "type": "boolean"
                },
                "size_bytes": {
                    "description": "new size (must be \u003e= current)",
                    "type": "integer"
                },
                "uid": {
                    "description": "new owner UID (0-65534)",
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
