apiVersion: v2
name: btrfs-nfs-csi
description: Kubernetes CSI driver that turns any btrfs filesystem into a full-featured NFS storage backend with instant snapshots, clones, and quotas
type: application
version: 0.2.0
appVersion: "0.10.0"
kubeVersion: ">=1.30.0-0"
home: https://github.com/erikmagkekse/btrfs-nfs-csi
sources:
  - https://github.com/erikmagkekse/btrfs-nfs-csi
keywords:
  - csi
  - btrfs
  - nfs
  - storage
  - snapshots
maintainers:
  - name: Erik Groh
    email: me@eriks.life
    url: https://github.com/erikmagkekse
annotations:
  org.opencontainers.image.title: btrfs-nfs-csi
  org.opencontainers.image.description: >-
    Kubernetes CSI driver that turns any btrfs filesystem into a full-featured
    NFS storage backend with instant snapshots, clones, and quotas
  org.opencontainers.image.url: https://github.com/erikmagkekse/btrfs-nfs-csi
  org.opencontainers.image.source: https://github.com/erikmagkekse/btrfs-nfs-csi
  org.opencontainers.image.documentation: https://github.com/erikmagkekse/btrfs-nfs-csi#readme
  org.opencontainers.image.licenses: Apache-2.0
  org.opencontainers.image.vendor: Erik Groh <me@eriks.life>
